# Generated by Django 6.0.4 on 2026-05-04 10:44

import courses.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('calendar_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Upraveno')),
            ],
            options={
                'db_table': 'calendar',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(help_text='Zadejte název kategorie', max_length=100, validators=[django.core.validators.RegexValidator(message='Zadejte prosím platný text.', regex="^[A-Za-zÀ-ž]+(?:[A-Za-zÀ-ž '\\-]*[A-Za-zÀ-ž])?$")], verbose_name='Název')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Upraveno')),
                ('parent_category', models.ForeignKey(blank=True, help_text='Napište nadřazenou kategorii. Pro vytvoření nadřazené kategorie ponechte tuto část nevyplněnou', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='courses.category', verbose_name='Nadřezená kategorie')),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Zadejte název kurzu', max_length=200, validators=[django.core.validators.RegexValidator(message='Zadejte prosím platný text.', regex="^[A-Za-zÀ-ž]+(?:[A-Za-zÀ-ž '\\-]*[A-Za-zÀ-ž])?$")], verbose_name='Název')),
                ('description', models.CharField(help_text='Stručně popište obsah kurzu', max_length=2000, verbose_name='Popis')),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], help_text='Vyberte úroveň náročnosti kurzu', max_length=12, verbose_name='Náročnost')),
                ('is_active', models.BooleanField(help_text='Určuje, jestli je kurz viditelný', verbose_name='Aktivní')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Upraveno')),
                ('category', models.ForeignKey(blank=True, help_text='Vyberte kategorii kurzu', null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.category', verbose_name='Kategorie')),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='CertificateType',
            fields=[
                ('certificate_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Zadejte název typu certifikátu', max_length=255, validators=[django.core.validators.RegexValidator(message='Zadejte prosím platný text.', regex="^[A-Za-zÀ-ž]+(?:[A-Za-zÀ-ž '\\-]*[A-Za-zÀ-ž])?$")], verbose_name='Název')),
                ('description', models.TextField(help_text='Zadejte popis certifikátu', verbose_name='Popis')),
                ('badge', models.CharField(help_text='Název odznaku certifikátu', verbose_name='Odznak')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Upraveno')),
                ('id_course', models.ForeignKey(help_text='Vyberte kurz, ke kterému certifikát patří', on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='Kurz')),
            ],
            options={
                'db_table': 'certificate_type',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id_education', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Zadejte název vzdělání', max_length=100, validators=[django.core.validators.RegexValidator(message='Zadejte prosím platný text.', regex="^[A-Za-zÀ-ž]+(?:[A-Za-zÀ-ž '\\-]*[A-Za-zÀ-ž])?$")], verbose_name='Vzdělání')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Upraveno')),
            ],
            options={
                'db_table': 'education',
                'indexes': [models.Index(fields=['name'], name='education_name_7b1bce_idx'), models.Index(fields=['id_education'], name='education_id_educ_137e95_idx'), models.Index(fields=['created_at'], name='education_created_a0bd2b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id_event', models.AutoField(primary_key=True, serialize=False)),
                ('is_global', models.BooleanField(help_text='Určuje, jestli je událost globální', verbose_name='Globální')),
                ('title', models.CharField(help_text='Zadejte název události', max_length=200, validators=[django.core.validators.RegexValidator(message='Zadejte prosím platný text.', regex="^[A-Za-zÀ-ž]+(?:[A-Za-zÀ-ž '\\-]*[A-Za-zÀ-ž])?$")], verbose_name='Název')),
                ('video_call_link', models.CharField(blank=True, help_text='Vložte odkaz na videohovor', max_length=2000, null=True, verbose_name='Odkaz na videohovor')),
                ('description', models.CharField(blank=True, help_text='Volitelný popis události', max_length=1000, null=True, verbose_name='Popis')),
                ('event_date', models.DateField(help_text='Zadejte datum události', verbose_name='Datum')),
                ('event_time', models.TimeField(help_text='Zadejte čas události', verbose_name='Čas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Upraveno')),
                ('id_calendar', models.ForeignKey(db_column='id_calendar', help_text='Vyberte kalendář události', on_delete=django.db.models.deletion.CASCADE, to='courses.calendar', verbose_name='Kalendář')),
                ('id_course', models.ForeignKey(blank=True, help_text='Volitelně vyberte kurz spojený s událostí', null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course', verbose_name='Kurz')),
            ],
            options={
                'db_table': 'event',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('lesson_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Zadejte název lekce', max_length=50, validators=[django.core.validators.RegexValidator(message='Zadejte prosím platný text.', regex="^[A-Za-zÀ-ž]+(?:[A-Za-zÀ-ž '\\-]*[A-Za-zÀ-ž])?$")], verbose_name='Název')),
                ('description', models.CharField(blank=True, help_text='Volitelný popis lekce', max_length=1000, null=True, verbose_name='Popis')),
                ('requirements', models.CharField(blank=True, help_text='Požadavky pro tuto lekci', max_length=200, null=True, verbose_name='Požadavky')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Upraveno')),
                ('course', models.ForeignKey(help_text='Vyberte kurz, ke kterému lekce patří', on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='Kurz')),
            ],
            options={
                'db_table': 'lesson',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id_module', models.AutoField(primary_key=True, serialize=False)),
                ('study_text', models.TextField(blank=True, help_text='Vložte studijní text modulu', null=True, verbose_name='Studijní text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Upraveno')),
                ('id_lesson', models.ForeignKey(db_column='id_lesson', help_text='Vyberte lekci, ke které modul patří', on_delete=django.db.models.deletion.CASCADE, to='courses.lesson', verbose_name='Lekce')),
            ],
            options={
                'db_table': 'module',
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('attachment_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_path', models.CharField(help_text='Zadejte cestu k souboru', max_length=255, verbose_name='Cesta k souboru')),
                ('file_name', models.CharField(help_text='Zadejte název souboru', max_length=255, verbose_name='Název souboru')),
                ('file_size', models.IntegerField(help_text='Zadejte velikost souboru v bajtech', validators=[django.core.validators.MinValueValidator(0, 'Velikost souboru nemůže být záporná')], verbose_name='Velikost souboru')),
                ('file_type', models.CharField(help_text='Zadejte MIME typ souboru', max_length=20, validators=[django.core.validators.RegexValidator(message='Zadejte platný typ souboru.', regex='^[\\w.+-]+/[\\w.+-]+$')], verbose_name='Typ souboru')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Upraveno')),
                ('module', models.ForeignKey(help_text='Vyberte modul, ke kterému příloha patří', on_delete=django.db.models.deletion.CASCADE, to='courses.module', verbose_name='Modul')),
            ],
            options={
                'db_table': 'attachment',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, help_text='Zadejte své křestní jméno', max_length=30, null=True, validators=[django.core.validators.RegexValidator(message='Zadejte prosím platný text.', regex="^[A-Za-zÀ-ž]+(?:[A-Za-zÀ-ž '\\-]*[A-Za-zÀ-ž])?$")], verbose_name='Křestní jméno')),
                ('last_name', models.CharField(blank=True, help_text='Zadejte své příjmení', max_length=30, null=True, validators=[django.core.validators.RegexValidator(message='Zadejte prosím platný text.', regex="^[A-Za-zÀ-ž]+(?:[A-Za-zÀ-ž '\\-]*[A-Za-zÀ-ž])?$")], verbose_name='Příjmení')),
                ('nickname', models.CharField(help_text='Zadejte svou přezdívku', max_length=30, validators=[django.core.validators.RegexValidator(message='Přezdívka může obsahovat jen písmena, čísla, tečku, podtržítko a pomlčku.', regex='^[A-Za-z0-9_.-]+$')], verbose_name='Přezdívka')),
                ('email', models.CharField(help_text='Zadejte svůj e-mail', max_length=100, validators=[django.core.validators.EmailValidator('Neplatný e-mail!')], verbose_name='E-mail')),
                ('password', models.CharField(help_text='Zadejte své heslo', max_length=255, verbose_name='Heslo')),
                ('bio', models.TextField(blank=True, help_text='Řekněte něco o sobě', null=True, verbose_name='Bio')),
                ('profile_photo', models.ImageField(blank=True, help_text='Nahrajte profilovou fotku', null=True, upload_to='profile-pics', verbose_name='Profilová fotka')),
                ('birthday', models.DateField(blank=True, help_text='Zadejte datum svého narození', null=True, validators=[courses.models.validate_birth_date], verbose_name='Narození')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Upraveno')),
                ('id_education', models.ForeignKey(blank=True, db_column='id_education', help_text='Vyberte dosažené vzdělání', null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.education', verbose_name='Vzdělání')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(help_text='Zadejte obsah zprávy', verbose_name='Obsah')),
                ('sent_at', models.DateTimeField(help_text='Zadejte datum a čas odeslání', verbose_name='Odesláno')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Upraveno')),
                ('receiver', models.ForeignKey(help_text='Vyberte příjemce zprávy', on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='courses.user', verbose_name='Příjemce')),
                ('sender', models.ForeignKey(help_text='Vyberte odesílatele zprávy', on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='courses.user', verbose_name='Odesílatel')),
            ],
            options={
                'db_table': 'message',
            },
        ),
        migrations.AddField(
            model_name='calendar',
            name='id_user',
            field=models.ForeignKey(help_text='Vyberte uživatele kalendáře', on_delete=django.db.models.deletion.CASCADE, to='courses.user', verbose_name='Uživatel'),
        ),
        migrations.CreateModel(
            name='UserCertificate',
            fields=[
                ('user_certificate_id', models.AutoField(primary_key=True, serialize=False)),
                ('issue_date', models.DateField(help_text='Zadejte datum vydání certifikátu', verbose_name='Datum vydání')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Upraveno')),
                ('certificate_type', models.ForeignKey(help_text='Vyberte typ certifikátu', on_delete=django.db.models.deletion.CASCADE, to='courses.certificatetype', verbose_name='Typ certifikátu')),
                ('user', models.ForeignKey(help_text='Vyberte uživatele certifikátu', on_delete=django.db.models.deletion.CASCADE, to='courses.user', verbose_name='Uživatel')),
            ],
            options={
                'db_table': 'user_certificate',
            },
        ),
        migrations.CreateModel(
            name='UsersInCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('teacher', 'Teacher'), ('student', 'Student')], help_text='Vyberte roli uživatele v kurzu', max_length=7, verbose_name='Role')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Upraveno')),
                ('course', models.ForeignKey(help_text='Vyberte kurz', on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='Kurz')),
                ('user', models.ForeignKey(help_text='Vyberte uživatele', on_delete=django.db.models.deletion.CASCADE, to='courses.user', verbose_name='Uživatel')),
            ],
            options={
                'db_table': 'users_in_course',
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['category_name'], name='category_categor_d484be_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent_category'], name='category_parent__5d838e_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['category_id'], name='category_categor_ad40b9_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['created_at'], name='category_created_74b871_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['created_at'], name='course_created_36d144_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_active'], name='course_is_acti_1229f3_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['course_id'], name='course_course__708290_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['title'], name='course_title_5c60ce_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['category'], name='course_categor_16662e_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['difficulty'], name='course_difficu_cfe0ad_idx'),
        ),
        migrations.AddIndex(
            model_name='certificatetype',
            index=models.Index(fields=['created_at'], name='certificate_created_bf8352_idx'),
        ),
        migrations.AddIndex(
            model_name='certificatetype',
            index=models.Index(fields=['name'], name='certificate_name_d0665e_idx'),
        ),
        migrations.AddIndex(
            model_name='certificatetype',
            index=models.Index(fields=['id_course'], name='certificate_id_cour_906abc_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['created_at'], name='event_created_989bde_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['id_event'], name='event_id_even_ffdd69_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['id_calendar'], name='event_id_cale_a60f39_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['title'], name='event_title_45e161_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_date'], name='event_event_d_b909d0_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['created_at'], name='lesson_created_aa1e06_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['title'], name='lesson_title_adfb0e_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['course'], name='lesson_course__c4014c_idx'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['created_at'], name='module_created_7eb570_idx'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['id_module'], name='module_id_modu_a094ae_idx'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['id_lesson'], name='module_id_less_ec991e_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['created_at'], name='attachment_created_5f4d6d_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['module'], name='attachment_module__2b5fa5_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['file_name'], name='attachment_file_na_30721e_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['attachment_id'], name='attachment_attachm_9a496f_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['file_type'], name='attachment_file_ty_374bd6_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['first_name', 'last_name'], name='user_first_n_3f9974_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['first_name'], name='user_first_n_65c305_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['id_education'], name='user_id_educ_3f20f8_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['created_at'], name='user_created_855a50_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['user_id'], name='user_user_id_31c9cf_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['created_at'], name='message_created_19da1c_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['message_id'], name='message_message_a8c1bc_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender'], name='message_sender__0e912c_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['receiver'], name='message_receive_bf3943_idx'),
        ),
        migrations.AddIndex(
            model_name='calendar',
            index=models.Index(fields=['created_at'], name='calendar_created_27ea5b_idx'),
        ),
        migrations.AddIndex(
            model_name='calendar',
            index=models.Index(fields=['calendar_id'], name='calendar_calenda_daff5f_idx'),
        ),
        migrations.AddIndex(
            model_name='calendar',
            index=models.Index(fields=['id_user'], name='calendar_id_user_fd2d9e_idx'),
        ),
        migrations.AddIndex(
            model_name='usercertificate',
            index=models.Index(fields=['created_at'], name='user_certif_created_e4033d_idx'),
        ),
        migrations.AddIndex(
            model_name='usercertificate',
            index=models.Index(fields=['user_certificate_id'], name='user_certif_user_ce_68d183_idx'),
        ),
        migrations.AddIndex(
            model_name='usercertificate',
            index=models.Index(fields=['issue_date'], name='user_certif_issue_d_8279e4_idx'),
        ),
        migrations.AddIndex(
            model_name='usersincourse',
            index=models.Index(fields=['created_at'], name='users_in_co_created_ae32b0_idx'),
        ),
        migrations.AddIndex(
            model_name='usersincourse',
            index=models.Index(fields=['role'], name='users_in_co_role_99c807_idx'),
        ),
        migrations.AddIndex(
            model_name='usersincourse',
            index=models.Index(fields=['course'], name='users_in_co_course__5078a1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usersincourse',
            unique_together={('user', 'course')},
        ),
    ]
