# Generated by Django 6.0.4 on 2026-05-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='img',
            field=models.ImageField(blank=True, help_text='Nahrajte miniaturu kurzu', null=True, upload_to='templates/img', verbose_name='Miniatura kurzu'),
        ),
    ]
